### ISSUE TITLE
predict_top_k interface  in caffe_mobile.cpp

### ISSUE THREAD

**Issue by StephenGuanqi** [sh1r0/caffe-android-lib#21]
Hi,I got a question about this interface.I just wanna acquire the prediction(prob) vector of one single channel(gray) image and I can not be quite understood of this interface.
What does the  function CHECK(ReadImageToDatum(img_path, 0, 256, 256, true, &datum))  mean and what kind of parameter should be passed into the ReadImageToDatum?And what does those parameter mean?Should I preprocess the image by myself?

Confusing about that,I give it a shot.I use CHECK(ReadImageToDatum(img_path, 0, 28, 28, false, &datum));   and then after compiled and running on the android device,the application crashed,with this

**Comment by StephenGuanqi** [comment]
interface run to the memory_data_layer->AddDatumVector(vector<Datum>({datum}));
Still I do not know what that mean and what is the result[1]->cpu_data()   ?

**Comment by sh1r0** [comment]
@StephenGuanqi  Sorry for the late response, I've been working on the new master branch intermittently since several months ago. Now, we do not need memory data layer in your deploy.prototxt and also image size and color depth are not hardcoded anymore. If you are still interested in this project, please have a look at the (new) master branch now. And if you have any problems, feel free to open a new issue.
Thanks.
