### ISSUE TITLE
Error while loading .so files

### ISSUE THREAD

**Issue by rj2101** [sh1r0/caffe-android-lib#39]
I tried to build the caffe libraries (libcaffe.so and libcaffe_jni.so) using eigen. The build was successful but while loading them into an android project i am getting the following error

cannot locate library reloc_library sigfillset.

Silmilar error also occured when loading libraries from github.com/sh1r0/caffe-android-demo repository. Some blogs suggested changing the android target version to 19 . I tried that but it didn't help. Original target was 21.

**Comment by keer2012** [comment]
Have you solved this issue?I ran into the same situation using my moto g .Need your help.@rj2101

**Comment by ZhengRui** [comment]
this is due to the low Android version in your mobile. The caffe-android and it's dependencies like opencv3 are build with ANDROID_NATIVE_API_LEVEL=21, and from [the official page](http://developer.android.com/ndk/guides/stable_apis.html) this only support android above 4.4w. In the beginning my phone is 4.4, and got the same issue, but after upgrade to 5, it works.

**Comment by sh1r0** [comment]
Hi @rj2101 and @keer2012 
As @ZhengRui said, your devices might have older versions of android which does not support android api 21. You both can try to build opencv 3 or opencv 2.4 with android api 19 on your own. I will not put extra efforts for supporting older deivecs. Sorry for the inconvenience caused.
