### ISSUE TITLE
About Eigen calculation speed in android 

### ISSUE THREAD

**Issue by fengFly2014** [sh1r0/caffe-android-lib#42]
Openblas is hard to compile in the form of JNI, and I use Eigen instead to calculate matrix multiplication in android 。directly use h file I compile Eigen to so file successfully。however，when calculating theresu of two matrix with dimension of 128*2028 and 2048*900 respectively in my phone HUAWEI glory 3C，the time consuming is about 1s，which is quite slow for me. I wonder if  I use Eigen properly or misuse it which leads to the long time calculation? thanks!

**Comment by fengFly2014** [comment]
with dimension of 128*2048 and 2048*900 .Great sorry

**Comment by fengFly2014** [comment]
with dimension of 128x2028 and 2048x900 .great sorry.

**Comment by sh1r0** [comment]
Sorry, I did not get the idea about your context. Is the problem is related to using caffe in android?

**Comment by fengFly2014** [comment]
@sh1r0 When Calculating matrix multiplication with dimension of 128x2028 and 2048x900 respectively in phone HUAWEI glory 3C,the library Eigen costs 1s,which is quite slow .I wonder if I use Eigen properly or misuse it which leads to the long time calculation.

**Comment by sh1r0** [comment]
Hmm... I mean to clarify that when the matrix multiplication you mentioned is performed, in fully-connected layers? Take caffenet as an example, a 4K * 4K matrix multiplication is performed during fc7 forwarding, however, I did not notice any performance issue before. Would you like to test OpenBLAS on your device to see if your issue is really caused by Eigen?

**Comment by sh1r0** [comment]
Any updates?
