### ISSUE TITLE
Suspected RAM insufficient problem

### ISSUE THREAD

**Issue by westpilgrim** [sh1r0/caffe-android-lib#47]
hi , I use your lib on my robot,but the app exits without any warning or information ,the RAM of the CPU is 1G .When I test the lib on my HUAWEI mate 8 ,whose RAM is 4G,everything was fine.

I traced the error and found that when the DNN is doing the forwarding : net_->ForwardFrom(0) ,the app crashes and exits .Loading DNN model was OK.

My problem is : does this means the robot cpu RAM runs out of RAM? how could I solve it apart from changing the cpus RAM ?

I compiled the lib using openblas

**Comment by westpilgrim** [comment]
I compiled the lib using openblas

**Comment by sh1r0** [comment]
I think that you encountered the out of memory issue. I used `adb shell dumpsys meminfo com.sh1r0.caffe_android_demo -d` to have a rough measure of native heap size, and the results showed that the native heap size was growing to more than 600 Mb during model loading phase.
Without enlarging your RAM, you could try on different models rather than caffenet, e.g., [Network in Network model](https://github.com/BVLC/caffe/wiki/Model-Zoo#network-in-network-model).
