### ISSUE TITLE
Why is Eigen no longer supported? 

### ISSUE THREAD

**Issue by huqinghao** [sh1r0/caffe-android-lib#84]
I wonder why is Eigen no longer supported?  Is there any bugs on Eigen?  I found that Eigen is unstable sometimes when using multi-threads.

**Comment by sh1r0** [comment]
First of all, Eigen is not officially supported in caffe, and thus not well tested (even unit tests). Second, the support of eigen before made things complex and not easy to maintain. Also, OpenBLAS is now available for arm-based android devices in this project. That's why Eigen is no longer supported.
